/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package graficacion;

import lists.ListaSdoble;

/**
 *
 * @author luis
 */
public class Inicio extends javax.swing.JFrame {
    
    private ListaSdoble _listaDeMetodos = new ListaSdoble();
    
    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        SortBox = new javax.swing.JComboBox();
        InsertBox = new javax.swing.JComboBox();
        DeleteBox = new javax.swing.JComboBox();
        SearchBox = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1250, 510));
        getContentPane().setLayout(null);

        jLabel1.setText("Sort");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(55, 47, 39, 25);

        jLabel2.setText("Insert");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(313, 45, 54, 29);

        jLabel3.setText("Delete");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(628, 47, 61, 25);

        jLabel4.setText("Search");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(914, 47, 62, 25);

        SortBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "BubbleSort", "SelectionSort", "InsertionSort", "MergeSort", "QuickSort", "HeapSort", "RaddixSort" }));
        SortBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SortBoxActionPerformed(evt);
            }
        });
        getContentPane().add(SortBox);
        SortBox.setBounds(55, 92, 171, 35);

        InsertBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "All sorted linked list", "Binary Search Tree", "AVL Tree", "Splay Tree", "Red-Black Tree" }));
        getContentPane().add(InsertBox);
        InsertBox.setBounds(313, 92, 231, 35);

        DeleteBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "All sorted linked list", "Binary Search Tree", "AVL Tree", "Splay Tree", "Red-Black Tree" }));
        getContentPane().add(DeleteBox);
        DeleteBox.setBounds(628, 92, 231, 35);

        SearchBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Binary Search", "Linear Search", "All sorted linked list", "Binary Search Tree", "AVL Tree", "Splay Tree", "Red-Black Tree" }));
        getContentPane().add(SearchBox);
        SearchBox.setBounds(914, 92, 231, 35);

        jLabel5.setText("Seleccione un algoritmo de las siguientes categorías");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(299, 8, 486, 25);

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("Metodos a calcular:\n");
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(50, 160, 1080, 250);

        jMenu1.setText("Archivo");

        jMenuItem1.setText("Ayuda");
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Salir");
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SortBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SortBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SortBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox DeleteBox;
    private javax.swing.JComboBox InsertBox;
    private javax.swing.JComboBox SearchBox;
    public static javax.swing.JComboBox SortBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
